version: "3.8"

services:
  app:
    build: .
    ports:
      - "5005:5005"
    volumes:
      - .:/app
    depends_on:
      - mongo
    devices:
      - "/dev/video0:/dev/video0"

  mongo:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    restart: always

volumes:
  mongodb_data_container: